version: '3'

services:
  app_crawler_linkedin_jobs_server:
    container_name: "app_crawler_linkedin_jobs_server"
    build:
      args:
        user: root
      context: ./services/web/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    env_file:
      - ./.env
    volumes:
      - ./services/web/:/app
    networks:
      - docker_crawler_linkedin_jobs_server

  app_crawler_linkedin_jobs_nginx:
    container_name: "app_crawler_linkedin_jobs_nginx"
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - app_crawler_linkedin_jobs_server
    volumes:
      - ./services/nginx/:/etc/nginx/conf.d/
    networks:
      - docker_crawler_linkedin_jobs_server

  app_crawler_linkedin_jobs_airflow:
    container_name: "app_crawler_linkedin_jobs_airflow"
    build:
      context: ./services/airflow
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./.env
    volumes:
      - ./services/airflow/dags:/opt/airflow/dags
    # entrypoint: ./services/airflow/entrypoint.sh

networks:
  docker_crawler_linkedin_jobs_server:
    driver: bridge
